[std]

train_file = '/tfrecords/cityscapes_train.tfrecord'
val_file = '/tfrecords/cityscapes_val.tfrecord'
pretrain = ''
log_code = 'cityscapes_1'
val_freq = 10
max_labels = 22

[model]

epochs = 50
batch_size = 2
lr = 1e-4
n_classes = 2
n_points = 5
img_size = [1024, 2048, 3]
n_pred = 25
kernel_initializer = 'glorot_uniform'
bias = true
patch_size = [400, 400, 3]
clf_dist = 2.5
halton = {x=[-85.39, 101.90], y=[-23.60, 2.8], z=[2.2, 383.0]}
