[std]

train_file = './data/tfrecords/cityscapes_train.tfrecord'
val_file = './data/tfrecords/cityscapes_val.tfrecord'
pretrain = ''
log_code = 'cityscapes_1'
val_freq = 10
max_labels = 22

[model]

epochs = 1000000
batch_size = 1
lr = 1e-4
n_classes = 9
n_points = 5
img_size = [1024, 2048, 3]
n_pred = 25
kernel_initializer = 'glorot_uniform'
bias = true
patch_size = [256, 256, 3]
clf_dist = 2.5
halton = {x=[-40.0, 0.0], y=[-1.5, 5.5], z=[-3.0, 140.0]}
