[std]

train_file = './data/kitti_car_train.tfrecord'
val_file = './data/kitti_car_train.tfrecord'
pretrain = ''
log_code = 'kitti_car_2_10'
val_freq = 10
max_labels = 20

[model]

epochs = 100
batch_size = 2
lr = 1e-4
n_classes = 2
n_points = 32768
img_size = [375, 1240, 3]
n_pred = 25
kernel_initializer = 'glorot_uniform'
bias = true
patch_size = [256, 256, 3]
clf_dist = 2.5
iou_border = 0.5
halton = {x=[-40.0, 0.0], y=[-1.5, 5.5], z=[-3.0, 140.0]}
